In [1]:
from pathlib import Path
import pandas as pd

In [2]:
BASE_DIR = Path().resolve().parent
df_sp500 = pd.read_csv(BASE_DIR / 'data' / 'raw_data' / 'sp500_raw' / 'sp500_master_50years.csv')

In [3]:
print(f"Rows: {df_sp500.shape[0]:,}")
print(f"Columns: {df_sp500.shape[1]}")

Rows: 1,014,000
Columns: 18

In [4]:
df_sp500.dtypes

Date                  str
Open              float64
High              float64
Low               float64
Close             float64
Volume              int64
Dividends         float64
Stock splits      float64
Ticker                str
Name                  str
Sector                str
Industry              str
Daily_return      float64
Monthly_return    float64
Sma200            float64
Sma50             float64
Volatility        float64
Weekly_return     float64
dtype: object

In [5]:
df_sp500.isnull().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Dividends             0
Stock splits          0
Ticker                0
Name                  0
Sector                0
Industry              0
Daily_return         98
Monthly_return     2040
Sma200            19714
Sma50              4864
Volatility         2913
Weekly_return       486
dtype: int64

In [6]:
df_sp500.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock splits,Ticker,Name,Sector,Industry,Daily_return,Monthly_return,Sma200,Sma50,Volatility,Weekly_return
0,1970-01-02 00:00:00-05:00,0.274696,0.290567,0.274696,0.290567,634838,0.0,0.0,BA,The Boeing Company,Industrials,Aerospace & Defense,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-02 00:00:00-05:00,1.258020,1.258020,1.224720,1.228419,276000,0.0,0.0,CAT,Caterpillar Inc.,Industrials,Farm & Heavy Construction Machinery,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-02 00:00:00-05:00,0.399793,0.408590,0.399793,0.408590,526400,0.0,0.0,CVX,Chevron Corporation,Energy,Oil & Gas Integrated,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-02 00:00:00-05:00,0.447662,0.448497,0.444321,0.444321,1109377,0.0,0.0,DIS,The Walt Disney Company,Communication Services,Entertainment,NaN,NaN,NaN,NaN,NaN,NaN
4,1970-01-02 00:00:00-05:00,0.637771,0.660433,0.637771,0.650721,60096,0.0,0.0,HON,Honeywell International Inc.,Industrials,Conglomerates,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_sp500.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock splits,Ticker,Name,Sector,Industry,Daily_return,Monthly_return,Sma200,Sma50,Volatility,Weekly_return
1013995,2026-02-20 00:00:00-05:00,49.029999,49.340000,48.529999,49.250000,25450100,0.0,0.0,VZ,Verizon Communications Inc.,Communication Services,Telecom Services,0.012541,0.255097,41.221361,41.968901,0.024826,-0.004246
1013996,2026-02-20 00:00:00-05:00,233.679993,234.050003,229.720001,230.309998,2388100,0.0,0.0,WM,"Waste Management, Inc.",Industrials,Waste Management,-0.013324,0.016866,221.918752,223.174200,0.011616,-0.003030
1013997,2026-02-20 00:00:00-05:00,123.000000,123.480003,121.050003,122.989998,35118900,0.0,0.0,WMT,Walmart Inc.,Consumer Defensive,Discount Stores,-0.015056,0.030412,105.080065,119.030014,0.018613,-0.079692
1013998,2026-02-20 00:00:00-05:00,150.490005,150.809998,146.460007,147.279999,25899900,0.0,0.0,XOM,Exxon Mobil Corporation,Energy,Oil & Gas Integrated,-0.024442,0.109660,114.641005,130.695973,0.018073,-0.017675
1013999,2026-02-20 00:00:00-05:00,126.330002,128.800003,125.599998,128.779999,5799000,0.0,0.0,ZTS,Zoetis Inc.,Healthcare,Drug Manufacturers - Specialty & Generic,0.011785,0.029581,141.327401,124.482218,0.013949,0.024992

In [8]:
print(f"First date: {df_sp500['Date'].min()}")
print(f"Last date:  {df_sp500['Date'].max()}")

First date: 1970-01-02 00:00:00-05:00
Last date:  2026-02-20 00:00:00-05:00

In [9]:
print(f"Unique tickers: {df_sp500['Ticker'].nunique()}")
df_sp500['Ticker'].value_counts().head(10)

Unique tickers: 98

Ticker
BA     14155
CAT    14155
CVX    14155
DIS    14155
HON    14155
IBM    14155
JNJ    14155
KO     14155
MCD    14155
MO     14155
Name: count, dtype: int64

In [10]:
df_sp500['Sector'].value_counts()

Sector
Healthcare                199279
Financial Services        148714
Technology                137041
Industrials               136807
Consumer Defensive        116871
Consumer Cyclical          80534
Communication Services     66608
Basic Materials            43210
Utilities                  36064
Energy                     28310
Real Estate                20562
Name: count, dtype: int64

In [12]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path().resolve().parent

df_clean = pd.read_csv(BASE_DIR / 'data' / 'processed_data' / 'sp500_clean.csv')

print(df_clean.shape)

print(df_clean[['cumulative_return', 'drawdown', 'price_vs_sma200', 
                'sharpe_proxy', 'crisis_period']].head(10))

(1014000, 23)
   cumulative_return  drawdown price_vs_sma200  sharpe_proxy crisis_period
0           1.000000  0.000000         no_data           NaN        normal
1           0.947830 -0.052170         no_data           NaN        normal
2           0.878261 -0.121739         no_data           NaN        normal
3           0.899999 -0.100001         no_data           NaN        normal
4           0.926092 -0.073908         no_data           NaN        normal
5           0.982610 -0.017390         no_data           NaN        normal
6           1.030433  0.000000         no_data           NaN        normal
7           1.073916  0.000000         no_data           NaN        normal
8           1.130435  0.000000         no_data           NaN        normal
9           1.234784  0.000000         no_data           NaN        normal